### ISSUE TITLE
how to init data

### ISSUE THREAD

**Issue by chenhailong118** [edwin404/html-multi-selector#1]
Hello,I want to init data use your control ui ,but wo do not know how to config the options 
 Please help me or your ui not have this function

**Comment by edwin404** [comment]
You can see the demo source and online live demo page here :
https://github.com/edwin404/html-multi-selector/tree/master/demo
http://edwin404.com/html-multi-selector/demo/

**Comment by chenhailong118** [comment]
请问你下，我想做的是初始化这个数据，比如默认值为北京市，市辖区，东城区，然后打开控件的时候，就能默认选中北京市，市辖区，东城区。现在我在你的demo中没有看到相关的说明，能否写一下啊？或者你的控件不支持这个。

**Comment by chenhailong118** [comment]
静态数据初始化(使用title)或者静态数据初始化(使用id)

**Comment by edwin404** [comment]
增加了两个Demo，可以参考一下。

**Comment by chenhailong118** [comment]
Thanks .
